import type { Metadata } from "next";
import Script from 'next/script'
import { Manrope } from "next/font/google";
import "./globals.css";
import { Header } from "./header";
import { Footer } from "./footer";

const manrope = Manrope({
  subsets: ["latin"],
  weight: ["400", "500", "700", "800"],
  display: "swap",
  variable: "--font-manrope",
});
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <link
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Outlined"
          rel="stylesheet"
        />
        <script src="https://cdn.tailwindcss.com?plugins=forms,container-queries" ></script>
        <script src="/app.js"></script>
      </head>
      <body className={`${manrope.variable} antialiased font-display bg-background-light dark:bg-background-dark text-[#111318] dark:text-gray-200`}>
        <div className="flex h-auto min-h-screen w-full flex-col group/design-root overflow-x-hidden">
          <div className="layout-container flex h-full grow flex-col">
            <Header />
            {children}
            <Footer />
          </div>
        </div>
      </body>
    </html >
  );
}
